### ISSUE TITLE
Выдать доступы на тестинг.

### ISSUE THREAD

**Issue by gebetix** [gebetix/smu5#2]
Создать профили пользователи их пароли, их папки, выдать права на доступ.

ssh 128.199.42.155

**Comment by gebetix** [comment]
Для Влада
user chomechome 
pass 12345

**Comment by gebetix** [comment]
Для Коли
user kobolok
pass 12345

**Comment by gebetix** [comment]
Отпишитесь есть ли у вас доступ и можете ли вы юзать судо. Если все ок я закрою таск.

**Comment by gebetix** [comment]
Ребята, отпишитесь здесь

**Comment by gebetix** [comment]
АУУУУ

**Comment by chomechome** [comment]
Все работает.

**Comment by makhalin** [comment]
С тобой же настраивали.
