### ISSUE TITLE
Создать и отправить pull request на шаблонную основу для сайта.

### ISSUE THREAD

**Issue by gebetix** [gebetix/smu5#4]
Просто пустой example Flask проекта.

Можно посмотреть в их репозитории и выбрать более подходящий.

**Comment by gebetix** [comment]
https://github.com/mitsuhiko/flask/tree/master/examples

**Comment by chomechome** [comment]
https://github.com/gebetix/smu5/pull/7

**Comment by gebetix** [comment]
давайте этот закроем уже таск и переедем в https://github.com/gebetix/smu5/issues/8
